version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/my-app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-package.json
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-package.json